In [1]:
import numpy as np
import pandas as pd

In [2]:
train = np.loadtxt(r'E:\Coding Ninjas Machine Learning and Deep Learning\PROJECT\Gradient Descent\Combined Cycle Power Plant\training_ccpp_x_y_train.csv',delimiter=',')

In [3]:
test =np.loadtxt(r'E:\Coding Ninjas Machine Learning and Deep Learning\PROJECT\Gradient Descent\Combined Cycle Power Plant\test_ccpp_x_test.csv',delimiter=',')

In [4]:
train.shape

(7176, 5)

In [5]:
test.shape

(2392, 4)

In [6]:
x_train = train[:,0:-1]
x_train

array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [7]:
y_train = train[:,-1]
y_train

array([482.26, 446.94, 452.56, ..., 437.65, 459.97, 444.42])

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
SC = StandardScaler()

In [11]:
SC.fit(x_train)

StandardScaler()

In [12]:
x_fit_train = SC.transform(x_train)

In [13]:
x_fit_test =SC.transform(test)

In [14]:
x_fit_test

array([[-1.02742256, -0.96138014,  0.72378329,  1.20446479],
       [-1.01136848, -1.25783726, -0.09942787,  0.57331371],
       [ 0.97398614,  1.62360048, -1.27807846,  0.39005424],
       ...,
       [ 0.62748557,  0.93814142, -0.69965107,  1.27284519],
       [ 0.51644485, -0.90099073,  0.11685368, -0.54470581],
       [ 0.28499852,  0.46914312,  0.95515424,  0.80580707]])

In [15]:
from sklearn.ensemble import GradientBoostingRegressor

In [21]:
algo=GradientBoostingRegressor(n_estimators=4000 , learning_rate=0.01)

In [22]:
algo.fit(x_fit_train,y_train)

GradientBoostingRegressor(learning_rate=0.01, n_estimators=4000)

In [23]:
predictions = algo.predict(x_fit_test)

In [24]:
predictions

array([470.31162905, 472.45962742, 435.94737185, ..., 437.54767551,
       455.32717086, 444.7176841 ])

In [25]:
np.savetxt('E:\Coding Ninjas Machine Learning and Deep Learning\PROJECT\Gradient Descent\Combined Cycle Power Plant\solution2.csv',predictions,fmt='%1.5f')