In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('0000000000002747_training_twitter_x_y_train.csv')
test = pd.read_csv('0000000000002747_test_twitter_x_test.csv')

In [3]:
train.head(1)

tweet_id airline_sentiment    airline airline_sentiment_gold  \
0  567900433542488064          negative  Southwest                    NaN   

            name negativereason_gold  retweet_count  \
0  ColeyGirouard                 NaN              0   

                                                text tweet_coord  \
0  @SouthwestAir I am scheduled for the morning, ...         NaN   

               tweet_created   tweet_location           user_timezone  
0  2015-02-17 20:16:29 -0800  Washington D.C.  Atlantic Time (Canada)

In [4]:
train.isnull().sum()

tweet_id                      0
airline_sentiment             0
airline                       0
airline_sentiment_gold    10949
name                          0
negativereason_gold       10956
retweet_count                 0
text                          0
tweet_coord               10204
tweet_created                 0
tweet_location             3550
user_timezone              3577
dtype: int64

In [5]:
tweet_df_train = pd.concat([train['text'],train['airline_sentiment']],axis=1)

In [6]:
tweet_df_train.head()

text airline_sentiment
0  @SouthwestAir I am scheduled for the morning, ...          negative
1  @SouthwestAir seeing your workers time in and ...          positive
2  @united Flew ORD to Miami and back and  had gr...          positive
3     @SouthwestAir @dultch97 that's horse radish 😤🐴          negative
4  @united so our flight into ORD was delayed bec...          negative

In [7]:
import re

In [8]:
# !pip install emoji --upgrade

In [9]:
# import emoji

In [10]:
tweet_df_train.isnull().sum()

text                 0
airline_sentiment    0
dtype: int64

In [11]:
tweet_df_train['airline_sentiment'].value_counts()

negative    6851
neutral     2327
positive    1802
Name: airline_sentiment, dtype: int64

In [12]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
tweet_df_train['airline_sentiment'] = le.fit_transform(tweet_df_train['airline_sentiment'])
tweet_df_train.head(2)

text  airline_sentiment
0  @SouthwestAir I am scheduled for the morning, ...                  0
1  @SouthwestAir seeing your workers time in and ...                  2

In [13]:
# tweet_df_train['airline_sentiment']=tweet_df_train['airline_sentiment'].apply(lambda x: sentiment_order.index(x))

In [14]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [15]:
# ps=PorterStemmer()

In [16]:
def tweetsToWords(tweet):
    letters = re.sub('[^a-zA-Z]',' ',tweet)
    words = letters.lower().split()
    stops = set(stopwords.words('english'))
    usefulWords = [w for w in words if w not in stops]
    return ' '.join(usefulWords)

In [17]:
tweet_df_train['clean_tweet'] = tweet_df_train['text'].apply(lambda x: tweetsToWords(x))


In [18]:
tweet_df_train.head()

text  airline_sentiment  \
0  @SouthwestAir I am scheduled for the morning, ...                  0   
1  @SouthwestAir seeing your workers time in and ...                  2   
2  @united Flew ORD to Miami and back and  had gr...                  2   
3     @SouthwestAir @dultch97 that's horse radish 😤🐴                  0   
4  @united so our flight into ORD was delayed bec...                  0   

                                         clean_tweet  
0  southwestair scheduled morning days fact yes s...  
1  southwestair seeing workers time time going be...  
2  united flew ord miami back great crew service ...  
3                   southwestair dultch horse radish  
4  united flight ord delayed air force one last f...

In [19]:
labels = np.array(tweet_df_train['airline_sentiment'])

In [20]:
labels

array([0, 2, 2, ..., 0, 0, 0])

In [21]:
tweet_df_train['clean_tweet']

0        southwestair scheduled morning days fact yes s...
1        southwestair seeing workers time time going be...
2        united flew ord miami back great crew service ...
3                         southwestair dultch horse radish
4        united flight ord delayed air force one last f...
                               ...                        
10975                               americanair followback
10976    united thanks help wish phone reps could accom...
10977             usairways worst ever dca customerservice
10978           nrhodes look another apology fly usairways
10979    united far worst airline plane delays round tr...
Name: clean_tweet, Length: 10980, dtype: object

In [22]:
train_document=[]
for ele in tweet_df_train['clean_tweet']:
    train_document.append(ele)

In [23]:
len(train_document)

10980

In [32]:
train_document

['southwestair scheduled morning days fact yes sure evening flight one cancelled flightled',
 'southwestair seeing workers time time going beyond love flying guys thank',
 'united flew ord miami back great crew service legs thanks',
 'southwestair dultch horse radish',
 'united flight ord delayed air force one last flight sbn mins landed',
 'united load us flying sardine knew pilots hours late flight incompetent beyond belief',
 'jetblue stock response delays frustrating poor cust serv amp told ppl wait amp come back',
 'jetblue nice hoping rack enough miles take trip seattle enjoy perfect latte city coffee',
 'united frankly worse customer service ever problems happen deal defines company never united',
 'southwestair yeah haha never one expensive much fun destinationdragons',
 'southwestair mco gt dca flight almost full people screwed msy dca cancelled flightation united usairways cancelled flight swa mistake',
 'jetblue easiest way get ticket receipt get one check get one online tha

In [24]:
# training_documents=tweet_df_train['clean_tweet'].values
# training_categories=tweet_df_train['airline_sentiment'].values
# testing_documents=test['clean_tweet'].values

In [25]:
# training_documents,len(training_documents)

In [26]:
# training_categories , len(training_categories)

In [27]:
# testing_documents , len(testing_documents)

In [28]:
test['clean_tweet'] = test['text'].apply(lambda x : tweetsToWords(x))

In [29]:
test_document=[]
for ele in test['clean_tweet']:
    test_document.append(ele)

In [30]:
len(test_document)

3660

In [31]:
test_document

['americanair car gng dfw pulled hr ago icy roads hold aa since hr reach arpt aa wat',
 'americanair plane land identical worse conditions grk according metars',
 'southwestair believe many paying customers left high dry reason flight cancelled flightlations monday bdl wow',
 'usairways legitimately say would rather driven cross country flown us airways',
 'americanair still response aa great job guys',
 'united developers flying tmrw morn w min layover earlier flight hr layover move',
 'usairways hello anyone',
 'usairways husainhaqqani mr husain u shld protest well one ur party member rehman malik delayed pia flight hours',
 'usairways likely flightaware says plane still durango departed',
 'americanair even give option hold say lines busy plz try late flightr',
 'united announcement pre boarding addresses mobility disability requires travel lot stuff preboard',
 'usairways really embarrassing asking complimentary drink snack detailed https co za xb h amp argued',
 'southwestair pass

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from nltk.classify.scikitlearn import SklearnClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import accuracy_score, confusion_matrix

In [34]:
# count vectorizer

cv = CountVectorizer(analyzer = "word")
train_features= cv.fit_transform(train_document)
test_features= cv.transform(test_document)

In [38]:
train_features

<10980x11471 sparse matrix of type '<class 'numpy.int64'>'
	with 107004 stored elements in Compressed Sparse Row format>

In [39]:
test_features

<3660x11471 sparse matrix of type '<class 'numpy.int64'>'
	with 33563 stored elements in Compressed Sparse Row format>

In [65]:
nb = MultinomialNB()
nb.fit(train_features,labels)
y_pred = nb.predict(train_features)
accuracy = accuracy_score(labels,y_pred)
print(accuracy)

0.8437158469945355


In [47]:

test_pred = le.inverse_transform(y_pred)
print(test_pred)
# np.savetxt("test_pred.csv",test_pred,fmt='%s')

['negative' 'positive' 'positive' ... 'negative' 'negative' 'negative']


In [49]:
clf = RandomForestClassifier(n_estimators = 200)
clf.fit(train_features,labels)
y_pred1 = clf.predict(train_features)
accuracy = accuracy_score(labels,y_pred1)
print(accuracy)

0.995719489981785


In [57]:
test_pred1 = le.inverse_transform(y_pred1)
# # np.savetxt("test_pred.csv",test_pred1,fmt='%s')

print(test_pred1)

['negative' 'positive' 'positive' ... 'negative' 'negative' 'negative']


In [62]:
np.unique(test_pred,return_counts=True)

(array(['negative', 'neutral', 'positive'], dtype=object),
 array([7876, 1588, 1516], dtype=int64))

In [61]:
np.unique(test_pred1,return_counts=True)

(array(['negative', 'neutral', 'positive'], dtype=object),
 array([6858, 2304, 1818], dtype=int64))

In [63]:
# tfidf
tf=TfidfVectorizer(max_features=3660, max_df=0.8, min_df=0.001)
x_train=tf.fit_transform(train_document)
x_test=tf.transform(test_document)
y_train=labels

In [70]:
# random forest
clf=RandomForestClassifier(n_estimators=2000)
clf.fit(x_train, y_train)
y_pred3=clf.predict(x_test)

In [71]:
y_pred3

array([0, 0, 0, ..., 0, 2, 0])

In [72]:
clf.score(x_train,y_train)

0.9906193078324226

In [73]:
test_pred2 = le.inverse_transform(y_pred3)

In [74]:
np.savetxt(fname='predicted_cv_rf.csv', X=test_pred, fmt='%s')
np.savetxt(fname='predicted_cv_nb.csv', X=test_pred1, fmt='%s')
np.savetxt(fname='predicted_tf_rf.csv', X=test_pred2, fmt='%s')